=== destrodevianne/l2jenergy-/dist/game/data/xsd/events.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="list">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="EventInInstance">
          <xs:complexType>
            <xs:attribute name="val" type="xs:boolean" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventInstanceFile">
          <xs:complexType>
            <xs:attribute name="val" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventTimeInterval">
          <xs:complexType>
            <xs:attribute name="val" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventRunningTime">
          <xs:complexType>
            <xs:attribute name="val" type="xs:unsignedByte" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventPlayersInTeams">
          <xs:complexType>
            <xs:attribute name="min" type="xs:unsignedByte" use="required" />
            <xs:attribute name="max" type="xs:unsignedByte" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventPlayerLevel">
          <xs:complexType>
            <xs:attribute name="min" type="xs:unsignedByte" use="required" />
            <xs:attribute name="max" type="xs:unsignedByte" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventParticipationTime">
          <xs:complexType>
            <xs:attribute name="val" type="xs:unsignedByte" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventRespawnTeleportDelay">
          <xs:complexType>
            <xs:attribute name="val" type="xs:unsignedByte" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventStartLeaveTeleportDelay">
          <xs:complexType>
            <xs:attribute name="val" type="xs:unsignedByte" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventParticipation">
          <xs:complexType>
            <xs:attribute name="val" type="xs:boolean" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventTakeItem">
          <xs:complexType>
            <xs:attribute name="id" type="xs:unsignedByte" use="required" />
            <xs:attribute name="count" type="xs:unsignedByte" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventEnabledKillBonus">
          <xs:complexType>
            <xs:attribute name="val" type="xs:boolean" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventKillBonusReward">
          <xs:complexType>
            <xs:attribute name="id" type="xs:unsignedByte" use="required" />
            <xs:attribute name="count" type="xs:unsignedShort" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventEffectsRemoval">
          <xs:complexType>
            <xs:attribute name="val" type="xs:unsignedByte" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" name="Team">
          <xs:complexType>
            <xs:attribute name="id" type="xs:unsignedByte" use="required" />
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="coordinates" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventReward">
          <xs:complexType>
            <xs:attribute name="id" type="xs:unsignedByte" use="required" />
            <xs:attribute name="count" type="xs:unsignedShort" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventRewardTeamTie">
          <xs:complexType>
            <xs:attribute name="val" type="xs:boolean" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventMageBuffs">
          <xs:complexType>
            <xs:attribute name="val" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventFighterBuffs">
          <xs:complexType>
            <xs:attribute name="val" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventRestrictItems">
          <xs:complexType>
            <xs:attribute name="val" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventRestrictSkills">
          <xs:complexType>
            <xs:attribute name="val" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventPotionsAllowed">
          <xs:complexType>
            <xs:attribute name="val" type="xs:boolean" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventScrollsAllowed">
          <xs:complexType>
            <xs:attribute name="val" type="xs:boolean" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventSummonByItemAllowed">
          <xs:complexType>
            <xs:attribute name="val" type="xs:boolean" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventTargetTeamMembersAllowed">
          <xs:complexType>
            <xs:attribute name="val" type="xs:boolean" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventRequireMinFragsToReward">
          <xs:complexType>
            <xs:attribute name="val" type="xs:boolean" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="EventMinFragsRequired">
          <xs:complexType>
            <xs:attribute name="val" type="xs:unsignedByte" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== destrodevianne/l2jenergy-/dist/game/configuration/events/tvt.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../data/xsd/events.xsd">
    <!-- Event in instance -->
    <!-- Default: true -->
    <EventInInstance val="true"/>
	
    <!-- Name of the instance file for TvT -->
	<!-- Default: coliseum.xml -->
    <EventInstanceFile val="coliseum.xml"/>
	
	<!-- Times TvT will occur (24h format) -->
    <!-- Default: 9:00,15:00,21:00,3:00 -->
    <EventTimeInterval val="03:00,06:00,09:00,12:00,15:00,18:00,21:00,00:00"/>
	
	<!-- Event running time (in minutes) -->
    <!-- Default: 5 -->
    <EventRunningTime val="5"/>
	
	<!-- Minimum and Maximum amount of players allowed in each team. -->
    <!-- Default: min=2 and max=20 -->
    <EventPlayersInTeams min="2" max="20"/>
	
	<!-- Minimum and Maximum level of players that may join the event. -->
    <!-- Default: min=1 and max=85 -->
    <EventPlayerLevel min="1" max="85"/>
	
	<!-- Registration timer from start of event (in minutes). -->
	<!-- Default: 3 -->
    <EventParticipationTime val="3"/>
	
	<!-- Respawn delay timer (in seconds). -->
	<!-- Default: 10 -->
    <EventRespawnTeleportDelay val="0"/>
	
	<!-- Exit delay timer (in seconds). -->
	<!-- Default: 10 -->
    <EventStartLeaveTeleportDelay val="10"/>

	<!-- Event Participation not Fee. Fee is not returned. -->
	<!-- Default: false -->
    <EventParticipation val="false"/>
	
	<!-- (itemId, count) Example: 57,100000 -->
	<!-- Default: 0,0 -->
    <EventTakeItem id="0" count="0"/>
	
	<!-- Event Kill Bonus -->
	<!-- Default: false -->
    <EventEnabledKillBonus val="false"/>

    <!-- Event Kill Bonus Reward -->
	<!-- Default: 57,2000 -->
    <EventKillBonusReward id="57" count="2000"/>
	
    <!-- Participant's effects handling on teleport/death. -->
    <!-- Effects lasting through death never removed. -->
    <!-- 0 - always remove all effects. -->
    <!-- 1 - remove all effects only during port to event (noblesse blessing can be used) -->
    <!-- 2 - never remove any effect -->
    <!-- Default: 0 -->
    <EventEffectsRemoval val="0"/>
	
	<!-- First Team = id, name, color name, coordinates Start/Death x,y,z location. -->
    <Team id="1" name="Blue" coordinates="148695,46725,-3414"/>

	<!-- Second Team = id, name, color name, coordinates Start/Death x,y,z location. -->
    <Team id="2" name="Red" coordinates="149999,46728,-3414"/>
	
	<!-- Reward for winning team. -->
    <EventReward id="57" count="10000"/>
	
	<!-- Should both teams get reward if there's a tie? -->
    <EventRewardTeamTie val="false"/>
	
	<!-- Mage-class participants will be buffed with those buffs each respawn -->
	<!-- Format: skill1Id,skill1Level;skill2Id,skill2Level... -->
	<!-- Example: 1504,1;1500,1;1501,1;1085,3 -->
    <EventMageBuffs val="1504,1;1500,1;1501,1;1085,3"/>
	
	<!-- Fighter-class participants will be buffed with those buffs each respawn -->
	<!-- Format: skill1Id,skill1Level;skill2Id,skill2Level... -->
	<!-- Example: 1504,1;1501,1;1502,1;1499,1 -->
    <EventFighterBuffs val="1504,1;1501,1;1502,1;1499,1"/>
		
    <EventRestrictItems val="0,0"/>
    
	<!-- Skills will be disabled for the duration of the game.-->
	<!-- Default: 840,841,842,5982,5983 (Flight transformations).-->
    <EventRestrictSkills val="840,841,842,5982,5983"/>

	<!-- Event Rules -->
    <EventPotionsAllowed val="false"/>
    <EventScrollsAllowed val="false"/>
    <EventSummonByItemAllowed val="false"/>
    <EventTargetTeamMembersAllowed val="false"/>

    <!-- Require Min Frags To Reward. -->
    <EventRequireMinFragsToReward val="false"/>
	
	<!-- Min Frags To Reward. -->
    <EventMinFragsRequired val="1"/>
</list>
