=== destrodevianne/l2jenergy-/dist/game/data/xsd/Messages.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="list">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="message" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="set" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="lang" use="optional"/>
                      <xs:attribute type="xs:string" name="val" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="id" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== destrodevianne/l2jenergy-/L2jEnergy/dist/game/data/translation/IA.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/Messages.xsd">
    <!-- ALL IA Messages -->
    <message id="dp_ia_skipping">
        <set lang="en" val=": Skipping waiting time ..." />
		<set lang="ru" val=": Пропуск времени ожидания ..." />
	</message>
    <message id="dp_ia_no_skip">
        <set lang="en" val=": You can't skip waiting time right now!" />
		<set lang="ru" val=": Вы не можете пропустить время ожидания прямо сейчас!" />
    </message>
    <message id="dp_ia_aborted">
        <set lang="en" val=": Fight has been aborted!" />
		<set lang="ru" val=": Бой был прерван!" />
    </message>
    <message id="dp_ia_no_aborted">
        <set lang="en" val=": You can't abort fight right now!" />
		<set lang="ru" val=": Вы не можете прекратить бой прямо сейчас!" />
    </message>
    <message id="dp_ia_minions">
        <set lang="en" val=": All minions have been deleted!" />
		<set lang="ru" val=": Все монстры были удалены!" />
    </message>
    <message id="dp_ia_no_minions">
	    <set lang="en" val=": You can't despawn minions right now!" />
		<set lang="ru" val=": Вы не можете уничтожить монстров прямо сейчас!" />
	</message>
	<!-- Antharas IA -->
	<message id="dp_ia_antharas_respaw">
	    <set lang="en" val=": Antharas has been respawned." />
		<set lang="ru" val=": Антарас возродился." />
	</message>
	<message id="dp_ia_antharas_live">
	    <set lang="en" val=": You can't respawn antharas while antharas is alive!" />
		<set lang="ru" val=": Вы не можете возродить Антараса, пока Антарас жив!" />
	</message>
	<!-- Baium IA -->
	<message id="dp_ia_baium_no_respawn">
	    <set lang="en" val=": You cant respawn Baium while Baium is alive!" />
		<set lang="ru" val=": Вы не можете возродить Баюма, пока Баюм жив!" />
	</message>
</list>

=== destrodevianne/l2jenergy-/L2jEnergy/dist/game/data/translation/ServerTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Server Test Messages -->
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/Messages.xsd">
    <message id="lang_current_successfully">
        <set lang="en" val="Language successfully set to:" />
		<set lang="ru" val="Язык успешно установлен на:" />
	</message>
    <message id="no_unstuck_in_jail">
        <set lang="en" val="You cannot use unstuck while you are in jail." />
		<set lang="ru" val="Вы не можете использовать бегство во время нахождения в тюрьме." />
    </message>
    <message id="unstuck_time_minutes">
        <set lang="en" val="You use Escape: %s% minutes." />
		<set lang="ru" val="Вы используете бегство: %s% минут." />
    </message>
    <message id="unstuck_time_seconds">
        <set lang="en" val="You use Escape: %s% seconds." />
		<set lang="ru" val="Вы используете бегство: %s% секунд." />
    </message>
    <message id="dp_handler_time">
        <set lang="en" val="Server time is: %s%" />
		<set lang="ru" val="Время сервера: %s%" />
    </message>
    <message id="dp_handler_hellbound_locked">
	    <set lang="en" val="Hellbound is currently locked." />
		<set lang="ru" val="В настоящее время Острова Ада заблокирован." />
	</message>
	<message id="dp_handler_hellbound_level">
	    <set lang="en" val="Hellbound level: %s%" />
		<set lang="ru" val="Уровень Острова Ада: %s%" />
	</message>
</list>

=== destrodevianne/l2jenergy-/dist/game/data/xml/translation/Clan.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/Messages.xsd">
    <!-- Clan Messages -->
    <message id="clan_create_units_fail">
        <set lang="en" val="You can't create any more sub-units of this type." />
		<set lang="ru" val="Вы не можете создавать какие-либо подэлементы этого типа." />
	</message>
    <message id="clan_leader_fail">
        <set lang="en" val="Leader is not correct." />
		<set lang="ru" val="Лидер неверен." />
    </message>
    <message id="clan_alliance_done">
        <set lang="en" val="Alliance %s% has been created." />
		<set lang="ru" val="Создан Альянс %s%." />
    </message>
    <message id="clan_academy_member_grade">
        <set lang="en" val="You cannot change academy member grade." />
		<set lang="ru" val="Вы не можете изменить класс члена академии." />
    </message>
    <message id="clan_file_transfer_error">
        <set lang="en" val="File transfer error." />
		<set lang="ru" val="Ошибка передачи файлов." />
    </message>
    <message id="clan_no_such">
	    <set lang="en" val="No such clan." />
		<set lang="ru" val="Нет такого клана." />
	</message>
	<message id="clan_no_war">
	    <set lang="en" val="You aren't at war with this clan." />
		<set lang="ru" val="Вы не воюете с этим кланом." />
	</message>
	<!-- Clan Hall Messages -->
	 <message id="ch_no_owner">
        <set lang="en" val="This clan hall has no owner, you cannot change the configuration." />
		<set lang="ru" val="В этом клан-холле нет владельца, вы не можете изменить конфигурацию." />
    </message>
    <message id="ch_cursed_weapon">
        <set lang="en" val="The wielder of a cursed weapon cannot receive outside heals or buffs." />
		<set lang="ru" val="Владелец проклятого оружия не может получить в клан-холле исцеления или баффы." />
    </message>
	<!-- Clan Hall Sieges Messages -->
	 <message id="chs_level_restriction">
        <set lang="en" val="Only clans of level %s% or higher may register for a Siegable Hall." />
		<set lang="ru" val="Только кланы уровня %s% или выше могут зарегистрироваться на Осаждаемый Холл." />
    </message>
    <message id="no_register_defender">
        <set lang="en" val="You cannot register as a defender because %s% is owned by NPC." />
		<set lang="ru" val="Вы не можете зарегистрироваться как защитник, потому что %s% принадлежит NPC." />
    </message>
	<!-- Frestress Messages -->
	<message id="fort_no_owner">
        <set lang="en" val="This fortress has no owner, you cannot change the configuration." />
		<set lang="ru" val="У этой крепости нет владельца, вы не можете изменить конфигурацию." />
    </message>
	<!-- Castle Messages -->
	 <message id="castle_no_lord_open_door">
        <set lang="en" val="Only Castle doors can be open." />
		<set lang="ru" val="Только двери замка могут быть открыты." />
	</message>
    <message id="castle_no_lord_closed_door">
        <set lang="en" val="Only Castle doors can be closed." />
		<set lang="ru" val="Только двери замка могут быть закрыты." />
    </message>
    <message id="castle_no_clan_own">
        <set lang="en" val="Your clan does not own a castle." />
		<set lang="ru" val="У вашего клана нет замка." />
    </message>
    <message id="castle_gate_closed">
        <set lang="en" val="The gate is being closed." />
		<set lang="ru" val="Врата закрываются." />
    </message>
    <message id="castle_manor_deactivated">
        <set lang="en" val="Manor system is deactivated." />
		<set lang="ru" val="Система фермерства деактивирована." />
    </message>
	<!-- Territory War Messages -->
    <message id="tw_not_register">
	    <set lang="en" val="Non participants can't pickup Territory Wards!" />
		<set lang="ru" val="Не участники не могут забрать Территориальные палатки!" />
	</message>
	<message id="tw_register_id">
	    <set lang="en" val="Registred TerrId: %s%." />
		<set lang="ru" val="Зарегистрированные ТеррИд: %s%." />
	</message>
	<message id="tw_no_points">
	    <set lang="en" val="No points for you!" />
		<set lang="ru" val="Нет очков для вас!" />
	</message>
	<message id="tw_jobs">
	    <set lang="en" val="Your Territory's jobs:" />
		<set lang="ru" val="Работа вашей территории:" />
	</message>
</list>

=== destrodevianne/l2jenergy-/L2jEnergy/dist/game/data/translation/Dimensional.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Dimensional Messages -->
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/Messages.xsd">
    <message id="dimensional_rift_full">
        <set lang="en" val="Rift is full. Try later.." />
		<set lang="ru" val="Разлом между мирами заполнен. Попробуй позже.." />
	</message>
    <message id="no_invite_in_rift">
        <set lang="en" val="You cannot invite a player when you are in the Dimensional Rift." />
		<set lang="ru" val="Вы не можете приглашать игрока, когда находитесь в Разломе между мирами." />
    </message>
    <message id="no_dismiss_player_in_rift">
        <set lang="en" val="You can't dismiss party member when you are in Dimensional Rift." />
		<set lang="ru" val="Вы не можете исключить члена пати, когда находитесь в Разломе между мирами." />
    </message>
</list>
