=== destrodevianne/l2jenergy-/dist/game/data/xsd/Messages.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="list">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="message" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="set" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="lang" use="optional"/>
                      <xs:attribute type="xs:string" name="val" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="id" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== destrodevianne/l2jenergy-/L2jEnergy/dist/game/data/translation/VoicedCommand.xml
<?xml version="1.0" encoding="UTF-8"?> 
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/Messages.xsd">
    <!-- voicedcommandhandlers  Messages -->
    <message id="dp_handler_usage_deposit_withdraw">
	    <set lang="en" val=".deposit (%s% Adena = %i% Goldbar) / .withdraw (%i% Goldbar = %s% Adena)" />
		<set lang="ru" val=".deposit (%s% Адена = %i% Золотые слитки) / .withdraw (%i% Золотые слитки = %s% Адена)" />
	</message>
	<message id="dp_handler_you_now_have_goldbar_and_adena">
	    <set lang="en" val="Thank you, you now have %i% Goldbar(s), and %s% less adena." />
		<set lang="ru" val="Спасибо, теперь у вас есть %i% Золотые слитки, и на %s% меньше Адены." />
	</message>
	<message id="dp_handler_you_not_have_enough_goldbars_convert">
	    <set lang="en" val="You do not have enough Adena to convert to Goldbar(s), you need %s% Adena." />
		<set lang="ru" val="У вас недостаточно Адены для конвертации в Золотые слитки, вам нужно %s% Адены." />
	</message>
	<message id="dp_handler_you_not_have_goldbars_into">
	    <set lang="en" val="You do not have any Goldbars to turn into %s% Adena." />
		<set lang="ru" val="У вас нет Золотых слитков, чтобы превратить в %s% Адену." />
	</message>
	<message id="dp_handler_usage_banchat_name">
	    <set lang="en" val="Usage: .banchat [name] [minutes]" />
		<set lang="ru" val="Применение: .banchat [name] [minutes]" />
	</message>
	<message id="dp_handler_player_not_online">
	    <set lang="en" val="Player not online!" />
		<set lang="ru" val="Игрока нет в онлайне!" />
	</message>
	<message id="dp_handler_player_already_punished">
	    <set lang="en" val="Player is already punished!" />
		<set lang="ru" val="Игрок уже наказан!" />
	</message>
	<message id="dp_handler_you_can_ban_yourself">
	    <set lang="en" val="You can't ban yourself!" />
		<set lang="ru" val="Вы не можете заблокировать чат себе!" />
	</message>
	<message id="dp_handler_you_can_ban_gm">
	    <set lang="en" val="You can't ban GM!" />
		<set lang="ru" val="Вы не можете заблокировать чат GM!" />
	</message>
	<message id="dp_handler_you_can_ban_moderator">
	    <set lang="en" val="You can't ban moderator!" />
		<set lang="ru" val="Вы не можете заблокировать чат модератору!" />
	</message>
	<message id="dp_handler_chat_banned_moderator">
	    <set lang="en" val="Chat banned by moderator %s%" />
		<set lang="ru" val="Чат заблокированый модератором %s%." />
	</message>
	<message id="dp_handler_player_chat_banned_for_minutes">
	    <set lang="en" val="Player %s% chat banned for %i% minutes." />
		<set lang="ru" val="Игроку %s% чат заблокирован на %i% минут(ы)." />
	</message>
	<message id="dp_handler_player_chat_banned_forever">
	    <set lang="en" val="Player %s% chat banned forever." />
		<set lang="ru" val="Игроку %s% чат заблокирован навсегда." />
	</message>
	<message id="dp_handler_player_not_found">
	    <set lang="en" val="Player not found!" />
		<set lang="ru" val="Игрок не найден!" />
	</message>
	<message id="dp_handler_usage_unbanchat_name">
	    <set lang="en" val="Usage: .unbanchat [name]" />
		<set lang="ru" val="Применение: .unbanchat [name]" />
	</message>
	<message id="dp_handler_player_not_chat_banned">
	    <set lang="en" val="Player is not chat banned!" />
		<set lang="ru" val="Игроку не заблокирован чат!" />
	</message>
	<message id="dp_handler_player_chat_unbanned">
	    <set lang="en" val="Player %s% chat unbanned." />
		<set lang="ru" val="Игроку %s% чат разблокирован." />
	</message>
	<message id="dp_handler_chat_unbanned_moderator">
	    <set lang="en" val="Chat unbanned by moderator %s%." />
		<set lang="ru" val="Чат разблокирован модератором  %s%." />
	</message>
	<message id="dp_handler_setvcmd_clan_privileges">
	    <set lang="en" val="Your clan privileges have been set to %s% by %i%." />
		<set lang="ru" val="Ваши права клана были установлены из %s% на %i%." />
	</message>
	<message id="dp_handler_usage_info_stats">
	    <set lang="en" val="Usage: .stats [player name]" />
		<set lang="ru" val="Применение: .stats [player name]" />
	</message>
    <message id="dp_handler_player_debug_on">
        <set lang="en" val="Debugging disabled." />
		<set lang="ru" val="Отладка отключена." />
    </message>
    <message id="dp_handler_player_debug_off">
        <set lang="en" val="Debugging enabled." />
		<set lang="ru" val="Отладка включена." />
    </message>
	<message id="dp_handler_lang_current_successfully">
        <set lang="en" val="Language successfully set to:" />
		<set lang="ru" val="Язык успешно изменен на:" />
    </message>
	<message id="dp_handler_hellbound_locked">
        <set lang="en" val="Hellbound is currently locked." />
		<set lang="ru" val="В настоящее время Остров Ада заблокирован." />
    </message>
    <message id="dp_handler_hellbound_level">
	    <set lang="en" val="Hellbound level: %s%" />
		<set lang="ru" val="Уровень Острова Ада: %s%" />
	</message>
</list>

=== destrodevianne/l2jenergy-/dist/game/data/translation/Action.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Action Messages -->
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/Messages.xsd">
    <message id="target_null">
        <set lang="en" val="Not selected any target." />
		<set lang="ru" val="Не выбрано ни одной цели." />
	</message>
    <message id="sit_forced">
        <set lang="en" val="A dark force beyond your mortal understanding makes your knees to shake when you try to stand up..." />
		<set lang="ru" val="Темная сила за пределами вашего смертного понимания заставляет ваши колени дрожать, когда вы пытаетесь встать ..." />
    </message>
    <message id="item_cannot_use">
        <set lang="en" val="You cannot use this item." />
		<set lang="ru" val="Вы не можете использовать этот элемент." />
    </message>
    <message id="remove_previous_connection">
        <set lang="en" val="Remove previous connections first." />
		<set lang="ru" val="Сначала удалите предыдущие подключения." />
    </message>
    <message id="get_item_pet_too_fast">
        <set lang="en" val="You get items from pet too fast." />
		<set lang="ru" val="Вы получаете предметы от питомца слишком быстро." />
    </message>
    <message id="give_item_pet_too_fast">
	    <set lang="en" val="You are giving items to pet too fast." />
		<set lang="ru" val="Вы даете предметы питомцу слишком быстро." />
	</message>
	<message id="depositing_too_fast">
	    <set lang="en" val="You depositing items too fast." />
		<set lang="ru" val="Вы ложите переметы слишком быстро." />
	</message>
	<message id="withdrawing_too_fast">
        <set lang="en" val="You are withdrawing items too fast." />
		<set lang="ru" val="Вы забираете предметы слишком быстро." />
	</message>
    <message id="trading_too_fast">
        <set lang="en" val="You are trading too fast." />
		<set lang="ru" val="Вы торгуете слишком быстро." />
    </message>
    <message id="buying_too_fast">
        <set lang="en" val="You are buying too fast." />
		<set lang="ru" val="Вы покупаете слишком быстро." />
    </message>
    <message id="refund_too_fast">
        <set lang="en" val="You are using refund too fast." />
		<set lang="ru" val="Вы используете возврат слишком быстро." />
    </message>
    <message id="buying_seeds_too_fast">
        <set lang="en" val="You are buying seeds too fast." />
		<set lang="ru" val="Вы покупаете семена слишком быстро." />
    </message>
    <message id="selling_too_fast">
	    <set lang="en" val="You are selling items too fast." />
		<set lang="ru" val="Вы продаете предметы слишком быстро." />
	</message>
	<message id="crystallizing_too_fast">
	    <set lang="en" val="You are crystallizing too fast." />
		<set lang="ru" val="Вы слишком быстро кристаллизируете предметы." />
	</message>
	<message id="destroying_items_too_fast">
        <set lang="en" val="You are destroying items too fast." />
		<set lang="ru" val="Вы слишком быстро уничтожаете предметы." />
	</message>
    <message id="no_adena_count">
        <set lang="en" val="You do not have enough Adena." />
		<set lang="ru" val="У вас недостаточно Адены." />
    </message>
    <message id="no_trade_mode">
        <set lang="en" val="That person is in trade refusal mode." />
		<set lang="ru" val="Этот игрок находится в режиме отказа от торговли." />
    </message>
    <message id="no_trade_in_olys">
        <set lang="en" val="A user currently participating in the Olympiad cannot accept or request a trade." />
		<set lang="ru" val="Игрок, который в настоящее время участвует в Олимпиаде, не может принять или запросить сделку." />
    </message>
    <message id="no_trade_in_chaotic_state">
        <set lang="en" val="You cannot trade while you are in a chaotic state." />
		<set lang="ru" val="Вы не можете торговать, пока находитесь в хаотическом состоянии." />
    </message>
    <message id="no_tradet_to_chaotic_target">
	    <set lang="en" val="You cannot request a trade while your target is in a chaotic state." />
		<set lang="ru" val="Вы не можете запросить сделку, пока ваша цель находится в хаотичном состоянии." />
	</message>
	<message id="no_drop_in_jail">
	    <set lang="en" val="You cannot drop items in Jail." />
		<set lang="ru" val="Вы не можете бросать предметы в тюрьме." />
	</message>
	<message id="no_trade_in_jail">
        <set lang="en" val="You cannot trade while you are in in Jail." />
		<set lang="ru" val="Вы не можете торговать, когда находитесь в тюрьме." />
	</message>
    <message id="no_invite_in_jail">
        <set lang="en" val="You cannot invite a player while is in Jail." />
		<set lang="ru" val="Вы не можете пригласить игрока в тюрьму." />
    </message>
    <message id="no_chat_in_jail">
        <set lang="en" val="You can not chat with players outside of the jail." />
		<set lang="ru" val="Вы не можете общаться с игроками вне тюрьмы." />
    </message>
    <message id="no_elemental_power_trading">
        <set lang="en" val="You cannot add elemental power while trading." />
		<set lang="ru" val="Вы не можете добавлять элементную мощность при торговле." />
    </message>
    <message id="no_recipe_while_trading">
        <set lang="en" val="You may not alter your recipe book while trading." />
		<set lang="ru" val="Вы не можете изменять свою книгу рецептов во время торговли." />
    </message>
    <message id="no_exchange_items">
	    <set lang="en" val="You cannot exchange items while trading." />
		<set lang="ru" val="Вы не можете обменивать товар во время торговли." />
	</message>
	<message id="no_create_while_trading">
	    <set lang="en" val="You cannot create items while trading." />
		<set lang="ru" val="Вы не можете создавать товары во время торговли." />
	</message>
	<message id="no_restart_while_trading">
        <set lang="en" val="Cannot restart while trading." />
		<set lang="ru" val="Невозможно перезайти во время торговли." />
	</message>
    <message id="transactions_disabled">
        <set lang="en" val="Transactions are disabled for your Access Level." />
		<set lang="ru" val="Транзакции отключены для вашего уровня доступа." />
    </message>
    <message id="no_pickup_mercenaries_party">
        <set lang="en" val="You cannot pickup mercenaries while in a party." />
		<set lang="ru" val="Вы не можете набирать наемников во время пати." />
    </message>
    <message id="no_pickup_mercenaries_lord">
        <set lang="en" val="Only the castle lord can pickup mercenaries." />
		<set lang="ru" val="Только Лорд замка может набирать наемников." />
    </message>
    <message id="password_no_repeated">
        <set lang="en" val="The new password doesn't match with the repeated one!" />
		<set lang="ru" val="Новый пароль не совпадает с повторным!" />
    </message>
    <message id="password_shorter">
	    <set lang="en" val="The new password is shorter than 3 chars! Please try with a longer one." />
		<set lang="ru" val="Новый пароль короче 3 символов! Попробуйте более длинный." />
	</message>
	<message id="password_longer">
	    <set lang="en" val="The new password is longer than 30 chars! Please try with a shorter one." />
		<set lang="ru" val="Новый пароль длиннее 30 символов! Попробуйте более короткий вариант." />
	</message>
	<message id="password_invalid">
        <set lang="en" val="Invalid password data! You have to fill all boxes." />
		<set lang="ru" val="Неверные данные пароля! Вы должны заполнить все поля." />
	</message>
    <message id="password_problem">
        <set lang="en" val="A problem occured while changing password!" />
		<set lang="ru" val="При смене пароля возникла проблема!" />
    </message>
    <message id="no_hero_speak">
        <set lang="en" val="Action failed. Heroes are only able to speak in the global channel once every 10 seconds." />
		<set lang="ru" val="Действие не выполнено. Герои могут говорить только в глобальном чате каждые 10 секунд." />
    </message>
    <message id="no_spam_channel">
        <set lang="en" val="Do not spam shout channel." />
		<set lang="ru" val="Не спам в общий чат." />
    </message>
    <message id="no_summon_wyvern_in_siege">
        <set lang="en" val="You cannot summon wyvern while in siege." />
		<set lang="ru" val="Вы не можете призвать Виверну, находясь на осаде." />
    </message>
    <message id="no_buff_adventurer">
	    <set lang="en" val="Only adventurers who have not completed their 3rd class transfer may receive these buffs." />
		<set lang="ru" val="Только искатели приключений, которые не закончили переход на третью професию, могут получить эти баффы." />
	</message>
	<message id="no_unstuck_in_jail">
	    <set lang="en" val="You cannot use unstuck while you are in jail." />
		<set lang="ru" val="Вы не можете использовать Бегство, пока находитесь в тюрьме." />
	</message>
	<message id="unstuck_time_minutes">
	    <set lang="en" val="You use Escape: %s% minutes." />
		<set lang="ru" val="Вы используете Бегство: %s% минут(ы)." />
	</message>
	<message id="unstuck_time_seconds">
	    <set lang="en" val="You use Escape: %s% seconds." />
		<set lang="ru" val="Вы используете Бегство: %s% секунд(ы)." />
	</message>
</list>

=== destrodevianne/l2jenergy-/L2jEnergy/dist/game/data/translation/SevenSigns.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Seven Signs Messages -->
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/Messages.xsd">
    <message id="ss_teleported_nearest_seal">
        <set lang="en" val="You have been teleported to the nearest town due to the beginning of the Seal Validation period." />
		<set lang="ru" val="Вы были телепортированы в ближайший город из-за начала периода проверки печати." />
	</message>
    <message id="ss_teleported_nearest_cabal">
        <set lang="en" val="You have been teleported to the nearest town because you have not signed for any cabal." />
		<set lang="ru" val="Вы были телепортированы в ближайший город, потому что вы не подписались на период Борьбы." />
    </message>
    <message id="ss_festival_ended_time">
        <set lang="en" val="The Festival of Darkness will end in %s% minute(s)." />
		<set lang="ru" val="Фестиваль Тьмы закончится через %s% минут(ы)." />
    </message>
    <message id="ss_festival_ended">
        <set lang="en" val="The festival has ended. Your party leader must now register your score before the next festival takes place." />
		<set lang="ru" val="Фестиваль Тьмы закончился. Ваш лидер пати должен теперь зарегистрировать ваш счет до следующего фестиваля." />
    </message>
    <message id="ss_remove_player">
        <set lang="en" val="You have been removed from the festival arena." />
		<set lang="ru" val="Вы были удалены с арены Фестиваля Тьмы." />
    </message>
    <message id="ss_remove_party">
	    <set lang="en" val="%s% has been removed from the upcoming Festival." />
		<set lang="ru" val="%s% был снят с предстоящего Фестиваля Тьмы." />
	</message>
	<message id="ss_no_logout_player">
	    <set lang="en" val="You cannot log out while you are a participant in a Festival." />
		<set lang="ru" val="Вы не можете выйти, пока вы являетесь участником Фестиваля Тьмы." />
	</message>
	<message id="ss_no_restart_player">
        <set lang="en" val="You cannot restart while you are a participant in a festival." />
		<set lang="ru" val="Вы не можете перезайти, пока вы являетесь участником Фестиваля Тьмы." />
    </message>
    <message id="ss_no_resurrect_player">
	    <set lang="en" val="You may not resurrect participants in a festival." />
		<set lang="ru" val="Вы не можете воскрешать участников Фестиваля Тьмы." />
	</message>
	<message id="ss_no_sign_up">
	    <set lang="en" val="You cannot sign up while a festival is in progress." />
		<set lang="ru" val="Вы не можете зарегистрироваться во время Фестиваля Тьмы." />
	</message>
	<message id="ss_no_register">
        <set lang="en" val="You cannot register a score while a festival is in progress." />
		<set lang="ru" val="Вы не можете зарегистрировать счет во время Фестиваля Тьмы." />
    </message>
    <message id="ss_no_contribute">
        <set lang="en" val="You do not have any blood offerings to contribute." />
		<set lang="ru" val="У вас нет предложений крови, чтобы внести свой вклад." />
    </message>
    <message id="ss_no_leave_party">
	    <set lang="en" val="Only the party leader can leave a festival when a party has minimum number of members." />
		<set lang="ru" val="Лидер пати может покинуть Фестиваль Тьмы, когда пати имеет минимальное количество членов." />
	</message>
	<message id="ss_no_bonus">
	    <set lang="en" val="Bonuses cannot be paid during the competition period." />
		<set lang="ru" val="Бонусы не могут быть выплачены в течение периода соревнований." />
	</message>
</list>

=== destrodevianne/l2jenergy-/dist/game/data/translation/Auctions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Auctions Messages -->
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/Messages.xsd">
    <message id="auction_wrong_conditions">
        <set lang="en" val="Wrong conditions." />
		<set lang="ru" val="Неправильные условия." />
	</message>
    <message id="auction_canceled">
        <set lang="en" val="Your auction has been canceled." />
		<set lang="ru" val="Ваш аукцион был отменен." />
    </message>
    <message id="auction_invalid">
        <set lang="en" val="Invalid Auction!" />
		<set lang="ru" val="Недействительный аукцион!" />
    </message>
    <message id="auction_invalid_bid">
        <set lang="en" val="Invalid bid!" />
		<set lang="ru" val="Недопустимая ставка!" />
    </message>
    <message id="auction_invalid_duration">
        <set lang="en" val="Invalid auction duration!" />
		<set lang="ru" val="Недопустимая продолжительность аукциона!" />
    </message>
    <message id="auction_bidded">
	    <set lang="en" val="You have been out bidded." />
		<set lang="ru" val="Вы были вне закона." />
	</message>
	<message id="auction_won">
	    <set lang="en" val="Congratulation you have won ClanHall!" />
		<set lang="ru" val="Поздравляем, вы выиграли Холл Клана!" />
	</message>
	<message id="auction_fast">
	    <set lang="en" val="You are bidding too fast." />
		<set lang="ru" val="Вы предлагаете ставку слишком быстро." />
	</message>
	<message id="auction_next">
	    <set lang="en" val="The next auction will begin on the %s%." />
		<set lang="ru" val="Следующий аукцион начнется на %s%." />
	</message>
</list>

=== destrodevianne/l2jenergy-/dist/game/data/xml/translation/Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Events Messages -->
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/Messages.xsd">
    <message id="event_you_want_participate_event">
        <set lang="en" val="Do you want to participating in the %s%?" />
		<set lang="ru" val="Желаете ли вы пригять участвие в %s%?" />
	</message>
    <message id="event_you_alredy_registred">
        <set lang="en" val="You are already registred!" />
		<set lang="ru" val="Вы уже зарегистрированы!" />
	</message>
	<!-- Status -->
	<message id="status_started">
	    <set lang="en" val="START" />
		<set lang="ru" val="Старт" />
	</message>
	<message id="status_finished">
	    <set lang="en" val="FINISHED" />
		<set lang="ru" val="Финиш" />
	</message>
</list>

=== destrodevianne/l2jenergy-/dist/game/data/translation/Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Events Messages -->
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/Messages.xsd">
    <message id="event_no_register_in_other_event">
        <set lang="en" val="Couldnt register you due other event participation." />
		<set lang="ru" val="Не удалось зарегистрироватся на участие в других ивентах." />
	</message>
    <message id="event_team_blue_full">
        <set lang="en" val="The Blue Team is full." />
		<set lang="ru" val="Синяя команда заполнена." />
    </message>
    <message id="event_team_red_full">
        <set lang="en" val="The Red Team is full." />
		<set lang="ru" val="Красная команда заполнена." />
    </message>
    <message id="event_time_register_over">
        <set lang="en" val="The registration period for this event is over." />
		<set lang="ru" val="Период регистрации для этого ивента завершен." />
    </message>
    <message id="event_max_ip_reached">
        <set lang="en" val="You have reached the maximum allowed participants per IP." />
		<set lang="ru" val="Вы достигли максимально допустимое количество участников на IP-адрес." />
    </message>
    <message id="event_no_logout">
	    <set lang="en" val="A superior power doesn't allow you to leave the event." />
		<set lang="ru" val="Превосходная мощность не позволяет вам покинуть ивент." />
	</message>
	<message id="event_team_need_points">
	    <set lang="en" val="Your team must have at least 10 points in total." />
		<set lang="ru" val="Ваша команда должна иметь не менее 10 баллов." />
	</message>
	<message id="event_no_participant">
        <set lang="en" val="That player is not an event participant." />
		<set lang="ru" val="Этот игрок не является участником ивента." />
    </message>
    <message id="event_no_observation">
        <set lang="en" val="Cannot use while current Event." />
		<set lang="ru" val="Невозможно использовать во время текущего ивента." />
    </message>
    <message id="event_no_observe_games">
	    <set lang="en" val="You can not observe games while registered on an event." />
		<set lang="ru" val="Вы не можете наблюдать за играми, зарегистрированными на ивента." />
	</message>
	<message id="event_no_unregister">
	    <set lang="en" val="You cannot unregister to this event." />
		<set lang="ru" val="Вы не можете отменить регистрацию из этого ивента." />
	</message>
</list>

=== destrodevianne/l2jenergy-/dist/game/data/translation/Handler.xml
<?xml version="1.0" encoding="UTF-8"?> 
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/Messages.xsd">
    <!-- HANDLER  Messages -->
    <message id="dp_handler_jail_error">
        <set lang="en" val="You cannot use this function while you are jailed." />
		<set lang="ru" val="Вы не можете использовать эту функцию во время заключения в тюрьме." />
	</message>
    <message id="dp_handler_time">
        <set lang="en" val="Server time is: %s%" />
		<set lang="ru" val="Время сервера: %s%" />
    </message>
    <message id="dp_handler_unstuck_time_m">
        <set lang="en" val="You use Escape: %s% minutes." />
		<set lang="ru" val="Вы используете Бегство: %s% минут(ы)." />
    </message>
    <message id="dp_handler_unstuck_time_s">
        <set lang="en" val="You use Escape: %s% seconds." />
		<set lang="ru" val="Вы используете Бегство: %s% секунд(ы)." />
    </message>
	<!-- Wedding  Messages -->
	<message id="dp_wedding_married">
        <set lang="en" val="Congratulations you are married!" />
		<set lang="ru" val="Поздравляем вы женаты!" />
	</message>
    <message id="dp_wedding_married_notice">
        <set lang="en" val="Congratulations to %s% and %i%! They have been married." />
		<set lang="ru" val="Поздравляем %s% и %i%! Они поженились." />
    </message>
    <message id="dp_wedding_declined">
        <set lang="en" val="You declined your partner's marriage request." />
		<set lang="ru" val="Вы отклонили запрос брака от своего партнера." />
    </message>
    <message id="dp_wedding_declined_notice">
        <set lang="en" val="Your partner declined your marriage request." />
		<set lang="ru" val="Ваш партнер отклонил ваш запрос на брак." />
    </message>
</list>

=== destrodevianne/l2jenergy-/dist/game/data/translation/CommunityBoard.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/Messages.xsd">
    <!-- TeleportBoard Messages -->
    <message id="community_board_services_disabled">
        <set lang="en" val="Services disabled." />
		<set lang="ru" val="Сервис отключен." />
	</message>
    <message id="communityboard_teleport_personal_point_only_premium">
        <set lang="en" val="Only Players with premium accounts can use the teleport point." />
		<set lang="ru" val="Только Игроки с премиум-аккаунтом могут использовать точки телепорта." />
	</message>
	<message id="communityboard_teleport_persoanl_point_outofcontrol">
        <set lang="en" val="You can not save a point in your state." />
		<set lang="ru" val="Нельзя сохранить точку в вашем состоянии." />
	</message>
	<message id="communityboard_teleport_persoanl_point_incombat">
        <set lang="en" val="You can not store the point in combat mode." />
		<set lang="ru" val="Нельзя сохранить точку в боевом режиме." />
	</message>
	<message id="communityboard_teleport_persoanl_point_state">
        <set lang="en" val="You can not save a bookmark in your state." />
		<set lang="ru" val="Вы не можете сохранить закладку в своем состоянии." />
	</message>
	<message id="communityboard_teleport_persoanl_point_forbidden_zone">
        <set lang="en" val="You can not save point in this location." />
		<set lang="ru" val="Нельзя сохранить точку в данной локации." />
	</message>
	<message id="communityboard_teleport_persoanl_point_name">
        <set lang="en" val="You did not enter the name of the bookmark!" />
		<set lang="ru" val="Вы не указали имя закладки!" />
	</message>
	<message id="communityboard_teleport_personal_point">
        <set lang="en" val="You can not save more than %s% point." />
		<set lang="ru" val="Вы не можете сохранить более %s% точок(и)." />
	</message>
	<message id="communityboard_teleport_point_level_min_max">
        <set lang="en" val="This point is only teleport players to the level of %s% to %c%." />
		<set lang="ru" val="Данная точка телепорта доступна только игрокам с уровнем от %s% до %c%." />
	</message>
	<message id="communityboard_teleport_point_pk_denied">
        <set lang="en" val="Players with karma can not be moved to this location." />
		<set lang="ru" val="Игроки с кармой не могут перемещаться в данную локацию." />
	</message>
	<message id="communityboard_teleport_point_only_premium">
        <set lang="en" val="Only Players with premium accounts can be moved to this location." />
		<set lang="ru" val="Только Игроки с премиум-аккаунтом могут перемещаться в данную локацию." />
	</message>
	<message id="communityboard_teleport_point_success_location">
        <set lang="en" val="You have successfully moved to the point %s%." />
		<set lang="ru" val="Вы успешно перемещены в точку %s%." />
	</message>
	<message id="communityboard_you_can_teleported_now">
        <set lang="en" val="You can't be teleported now" />
		<set lang="ru" val="Вы не можете быть телепортированы сейчас" />
	</message>
	<message id="communityboard_teleport_point_success_location">
        <set lang="en" val="You have successfully moved to the point %s%" />
		<set lang="ru" val="Вы успешно перемещены в точку %s%" />
	</message>
	<message id="communityboard_teleport_dont_have_points">
        <set lang="en" val="You don't have points!" />
		<set lang="ru" val="У вас нет сохраненных точек!" />
	</message>
</list>
