=== destrodevianne/l2jenergy-/L2jEnergy/dist/game/data/xsd/product.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="list">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="product" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="item">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:short" name="id" use="optional"/>
                      <xs:attribute type="xs:byte" name="count" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:int" name="id" use="optional"/>
            <xs:attribute type="xs:string" name="name" use="optional"/>
            <xs:attribute type="xs:byte" name="category" use="optional"/>
            <xs:attribute type="xs:short" name="price" use="optional"/>
            <xs:attribute type="xs:string" name="on_sale" use="optional"/>
			<xs:attribute type="xs:string" name="is_event" use="optional"/>
			<xs:attribute type="xs:string" name="is_best" use="optional"/>
			<xs:attribute type="xs:string" name="is_new" use="optional"/>
            <xs:attribute type="xs:string" name="sale_start_date" use="optional"/>
            <xs:attribute type="xs:string" name="sale_end_date" use="optional"/>
			<xs:attribute type="xs:byte" name="day_of_week" use="optional"/>
			<xs:attribute type="xs:byte" name="max_stock" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== destrodevianne/l2jenergy-/L2jEnergy/dist/game/data/itemMall/Other.xml
<?xml version='1.0' encoding='utf-8'?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/product.xsd">
    <product id="1080001" name="Queen Ant Ring" category="5" price="10" is_best="true" on_sale="true">
		<item id="6660" count="1" />
	</product>
	<product id="1080002" name="Middle fortuna box" category="5" price="270" is_best="true" on_sale="true">
		<item id="22001" count="1" />
	</product>
	<product id="1080003" name="Large fortuna box" category="5" price="405" is_best="true" on_sale="true">
		<item id="22002" count="1" />
	</product>
	<product id="1080004" name="Huge Fortuna Box" category="5" price="610" is_best="true" on_sale="true">
		<item id="20515" count="1" />
	</product>
	<product id="1080005" name="Small fortuna cube" category="5" price="81" is_best="true" on_sale="true">
		<item id="22003" count="1" />
	</product>
	<product id="1080006" name="Middle fortuna cube" category="5" price="216" is_best="true" on_sale="true">
		<item id="22004" count="1" />
	</product>
	<product id="1080007" name="Large fortuna cube" category="5" price="324" is_best="true" on_sale="true">
		<item id="22005" count="1" />
	</product>
	<product id="1080008" name="Huge Fortuna Cube" category="5" price="524" is_best="true" on_sale="true">
		<item id="20516" count="1" />
	</product>
	<product id="1080009" name="Allegra Box" category="5" price="139" is_best="true" on_sale="true">
		<item id="22310" count="1" />
	</product>
	<product id="1080010" name="Latus Box" category="5" price="279" is_best="true" on_sale="true">
		<item id="22311" count="1" />
	</product>
</list>

=== destrodevianne/l2jenergy-/L2jEnergy/dist/game/data/itemMall/Package.xml
<?xml version='1.0' encoding='utf-8'?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/product.xsd">
	<product id="1080049" name="A Scroll Bundle of Fighter" category="4" price="52" on_sale="true">
		<item id="22087" count="1" />
	</product>
	<product id="1080050" name="A Scroll Bundle of Mage" category="4" price="59" on_sale="true">
		<item id="22088" count="1" />
	</product>
	<product id="1080140" name="Beast Soulshot Pack" category="4" price="14" is_new="true" on_sale="true">
		<item id="20326" count="1" />
	</product>
	<product id="1080141" name="Beast Spiritshot Pack" category="4" price="11" is_new="true" on_sale="true">
		<item id="20327" count="1" />
	</product>
	<product id="1080229" name="Hunting Helper Exchange Coupon - 1 sheet" category="4" price="169" is_new="true" on_sale="true">
		<item id="13273" count="1" />
	</product>
	<product id="1080230" name="Hunting Helper Exchange Coupon - 3 sheet" category="4" price="506" is_new="true" on_sale="true">
		<item id="13273" count="3" />
	</product>
	<product id="1080233" name="Steam Beatle Mounting Bracelet 7 Day Pack" category="4" price="2695" is_new="true" on_sale="true">
		<item id="14232" count="1" />
	</product>
	<product id="1080234" name="Light Purple Maned Horse Bracelet 30 Day Pack" category="4" price="2695" is_best="true" is_new="true" on_sale="true">
		<item id="20059" count="1" />
	</product>
</list>

=== destrodevianne/l2jenergy-/L2jEnergy/dist/game/data/itemMall/Decorating.xml
<?xml version='1.0' encoding='utf-8'?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/product.xsd">
	<product id="1080201" name="Sudden Agathion 7 Day Pack" category="3" price="338" is_new="true" on_sale="true" max_stock="1">
		<item id="139" count="1" />
	</product>
	<product id="1080202" name="Shiny Agathion 7 Day Pack" category="3" price="338" is_new="true" on_sale="true" max_stock="1">
		<item id="140" count="1" />
	</product>
	<product id="1080203" name="Sobbing Agathion 7 Day Pack" category="3" price="338" is_new="true" on_sale="true" max_stock="1">
		<item id="141" count="1" />
	</product>
	<product id="1080204" name="Agathion of Love 7 Day Pack" category="3" price="228" is_new="true" on_sale="true" max_stock="1">
		<item id="13280" count="1" />
	</product>
	<product id="1080205" name="Pumpkin Transformation Stick 7 Day Pack" category="3" price="254" is_new="true" on_sale="true" max_stock="1">
		<item id="13281" count="1" />
	</product>
	<product id="1080206" name="Kat the Cat Hat 7 Day Pack" category="3" price="169" is_new="true" on_sale="true">
		<item id="13282" count="1" />
	</product>
	<product id="1080207" name="Feline Queen Hat 7 Day Pack" category="3" price="169" is_new="true" on_sale="true">
		<item id="13283" count="1" />
	</product>
	<product id="1080208" name="Monster Eye Hat 7 Day Pack" category="3" price="169" is_new="true" on_sale="true">
		<item id="13284" count="1" />
	</product>
	<product id="1080209" name="Brown Bear Hat 7 Day Pack" category="3" price="169" is_new="true" on_sale="true">
		<item id="13285" count="1" />
	</product>
	<product id="1080210" name="Fungus Hat 7 Day Pack" category="3" price="169" is_new="true" on_sale="true">
		<item id="13286" count="1" />
	</product>
	<product id="1080211" name="Skull Hat 7 Day Pack" category="3" price="169" is_new="true" on_sale="true">
		<item id="13287" count="1" />
	</product>
	<product id="1080212" name="Ornithomimus Hat 7 Day Pack" category="3" price="169" is_new="true" on_sale="true">
		<item id="13288" count="1" />
	</product>
	<product id="1080213" name="Feline King Hat 7 Day Pack" category="3" price="169" is_new="true" on_sale="true">
		<item id="13289" count="1" />
	</product>
	<product id="1080214" name="Kai the Cat Hat 7 Day Pack" category="3" price="169" is_new="true" on_sale="true">
		<item id="13290" count="1" />
	</product>
	<product id="1080215" name="Goggle Pack" category="3" price="338" is_new="true" on_sale="true">
		<item id="20315" count="1" />
	</product>
	<product id="1080216" name="Napoleon Hat Pack" category="3" price="338" is_best="true" is_new="true" on_sale="true">
		<item id="20316" count="1" />
	</product>
	<product id="1080217" name="Black Gem Mask Pack" category="3" price="338" is_new="true" on_sale="true">
		<item id="20318" count="1" />
	</product>
	<product id="1080218" name="Afro Hair Pack - Gold" category="3" price="338" is_new="true" on_sale="true">
		<item id="20278" count="1" />
	</product>
	<product id="1080219" name="Afro Hair Pack - Pink" category="3" price="338" is_new="true" on_sale="true">
		<item id="20279" count="1" />
	</product>
	<product id="1080220" name="Horn Rimmed Glasses Pack" category="3" price="338" is_new="true" on_sale="true">
		<item id="20045" count="1" />
	</product>
	<product id="1080221" name="Afro Hair Pack " category="3" price="338" is_new="true" on_sale="true">
		<item id="20046" count="1" />
	</product>
	<product id="1080222" name="Afro Hair Pack - Big Head, Firework" category="3" price="338" is_new="true" on_sale="true">
		<item id="20047" count="1" />
	</product>
	<product id="1080223" name="Afro Hair Pack - Wind Walk" category="3" price="338" is_new="true" on_sale="true">
		<item id="20048" count="1" />
	</product>
	<product id="1080224" name="Uniform Hat Pack" category="3" price="338" is_new="true" on_sale="true">
		<item id="20049" count="1" />
	</product>
	<product id="1080225" name="Assassins Bamboo Hat Pack" category="3" price="338" is_new="true" on_sale="true">
		<item id="20050" count="1" />
	</product>
	<product id="1080226" name="Ruthless Tribe Mask Pack" category="3" price="338" is_new="true" on_sale="true">
		<item id="20051" count="1" />
	</product>
	<product id="1080227" name="Ribbon Hairband Pack" category="3" price="338" is_new="true" on_sale="true">
		<item id="20052" count="1" />
	</product>
	<product id="1080228" name="Visor Pack" category="3" price="338" is_new="true" on_sale="true">
		<item id="20053" count="1" />
	</product>
</list>

=== destrodevianne/l2jenergy-/dist/game/data/itemMall/Runes.xml
<?xml version='1.0' encoding='utf-8'?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/product.xsd">
	<product id="1080112" name="Rune of Exp. Points 30% - 5 hours" category="1" price="33" on_sale="true">
		<item id="20335" count="1" />
	</product>
	<product id="1080113" name="Rune of Exp. Points 50% - 5 hours" category="1" price="54" on_sale="true">
		<item id="20336" count="1" />
	</product>
	<product id="1080114" name="Rune of Exp. Points 30% - 10 hours" category="1" price="52" on_sale="true" is_event="true">
		<item id="20337" count="1" />
	</product>
	<product id="1080115" name="Rune of Exp. Points 50% - 10 hours" category="1" price="87" on_sale="true">
		<item id="20338" count="1" />
	</product>
	<product id="1080116" name="Rune of Exp. Points 30% - 7 days" category="1" price="697" on_sale="true">
		<item id="20339" count="1" />
	</product>
	<product id="1080117" name="Rune of Exp. Points 50% - 7 days" category="1" price="1161" on_sale="true">
		<item id="20340" count="1" />
	</product>
	<product id="1080118" name="Rune of SP 30% - 5 hours" category="1" price="17" on_sale="true">
		<item id="20341" count="1" />
	</product>
	<product id="1080119" name="Rune of SP 50% - 5 hours" category="1" price="27" on_sale="true">
		<item id="20342" count="1" />
	</product>
	<product id="1080120" name="Rune of SP 30% - 10 hours" category="1" price="26" on_sale="true">
		<item id="20343" count="1" />
	</product>
	<product id="1080121" name="Rune of SP 50% - 10 hours" category="1" price="44" on_sale="true">
		<item id="20344" count="1" />
	</product>
	<product id="1080122" name="Rune of SP 30% - 7 days" category="1" price="349" on_sale="true">
		<item id="20345" count="1" />
	</product>
	<product id="1080123" name="Rune of SP 50% - 7 days" category="1" price="581" on_sale="true">
		<item id="20346" count="1" />
	</product>
	<product id="1080124" name="Rune of Crystal level 3 - 5 hours" category="1" price="33" on_sale="true">
		<item id="20347" count="1" />
	</product>
	<product id="1080125" name="Rune of Crystal level 5 - 5 hours" category="1" price="54" on_sale="true">
		<item id="20348" count="1" />
	</product>
	<product id="1080126" name="Rune of Crystal level 3 - 10 hours" category="1" price="52" on_sale="true">
		<item id="20349" count="1" />
	</product>
	<product id="1080127" name="Rune of Crystal level 5 - 10 hours" category="1" price="87" on_sale="true">
		<item id="20350" count="1" />
	</product>
	<product id="1080128" name="Rune of Crystal level 3 - 7 days" category="1" price="697" on_sale="true">
		<item id="20351" count="1" />
	</product>
	<product id="1080129" name="Rune of Crystal level 5 - 7 days" category="1" price="1161" on_sale="true">
		<item id="20352" count="1" />
	</product>
	<product id="1080130" name="Weapon-type Enhance Backup Stone (D-Grade) " category="1" price="21" on_sale="true">
		<item id="12362" count="1" />
	</product>
	<product id="1080131" name="Weapon-type Enhance Backup Stone (C-Grade) " category="1" price="45" on_sale="true">
		<item id="12363" count="1" />
	</product>
	<product id="1080132" name="Weapon-type Enhance Backup Stone (B-Grade) " category="1" price="203" on_sale="true">
		<item id="12364" count="1" />
	</product>
	<product id="1080133" name="Weapon-type Enhance Backup Stone (A-Grade) " category="1" price="729" on_sale="true">
		<item id="12365" count="1" />
	</product>
	<product id="1080134" name="Weapon-type Enhance Backup Stone (S-Grade) " category="1" price="2025" on_sale="true">
		<item id="12366" count="1" />
	</product>
	<product id="1080135" name="Armor-type Enhance Backup Stone (D-Grade) " category="1" price="4" on_sale="true">
		<item id="12367" count="1" />
	</product>
	<product id="1080136" name="Armor-type Enhance Backup Stone (C-Grade) " category="1" price="7" on_sale="true">
		<item id="12368" count="1" />
	</product>
	<product id="1080137" name="Armor-type Enhance Backup Stone (B-Grade) " category="1" price="29" on_sale="true">
		<item id="12369" count="1" />
	</product>
	<product id="1080138" name="Armor-type Enhance Backup Stone (A-Grade) " category="1" price="104" on_sale="true">
		<item id="12370" count="1" />
	</product>
	<product id="1080139" name="Armor-type Enhance Backup Stone (S-Grade) " category="1" price="290" on_sale="true">
		<item id="12371" count="1" />
	</product>
</list>
